"""
Event message definitions for the trading system.

Contains the base event message class, inheritance mixins for instrument- and
order-related events, and the `DomainEvents` and `SystemEvents` namespace classes
that group all concrete event message types that are used for communications between
system components.
"""

# fmt: off
from dataclasses    import dataclass, field
from time           import time_ns
from uuid           import UUID
# fmt: on


from .enums import TradeSide
from .instruments import InstrumentBase
from .types import (
    UnixNs,
    Reason,
    ScaledPrice,
    Quantity,
    SignedPositionSize,
    BarInterval,
    DataSource,
    Volume,
)


@dataclass(frozen=True, kw_only=True)
class EventMessageBase:
    """
    Base class for all event messages.

    Each event message carries at least the timestamp of its creation.

    Parameters:
        timestamp: Timestamp of event creation.
    """

    timestamp: UnixNs = field(default_factory=time_ns)


@dataclass(frozen=True, kw_only=True)
class InstrumentRelated:
    """
    Mixin for event message associated with a specific instrument.

    Should only be used alongside `EventMessageBase` via multiple inheritance.

    Parameters:
        instrument:
            The specific instrument this event relates to.
    """

    instrument: InstrumentBase


@dataclass(frozen=True, kw_only=True)
class OrderRelated:
    """
    Mixin for event message associated with a specific order via its order ID.

    Should only be used alongside `EventMessageBase` via multiple inheritance.

    Parameters:
        order_id:
            Unique system-internal identifier of the order this event relates to.
    """

    order_id: UUID


class DomainEvents:
    """
    Namespace class for domain-related event messages.
    """

    @dataclass(frozen=True, kw_only=True)
    class NewBar(EventMessageBase, InstrumentRelated):
        """
        Event message indicating that a new price bar has completed for the given
        instrument and bar aggregation interval.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            period_start:
                Timestamp marking the beginning of the bar's aggregation period.
            bar_interval:
                Time unit and multiplier defining the bar's aggregation period.
            open:
                Opening price of the bar.
            high:
                Highest price during the bar.
            low:
                Lowest price during the bar.
            close:
                Closing price of the bar.
            volume:
                Number of contracts or shares traded during the bar.
            data_source:
                Origin of the market data (e.g., information about datafeed provider
                and exchange).
        """

        # fmt: off
        period_start:   UnixNs
        bar_interval:   BarInterval

        open:           ScaledPrice
        high:           ScaledPrice
        low:            ScaledPrice
        close:          ScaledPrice
        volume:         Volume

        data_source:    DataSource
        # fmt: on

    @dataclass(frozen=True, kw_only=True)
    class OrderRequest(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that the trading system requests to submit an order
        for the given instrument.

        Only limit and stop-limit orders are supported.
        Market orders and plain stop orders must be expressed as their limit
        counterparts with marketable limit prices.

        A limit order is created when only `limit_price` is set.
        A stop-limit order is created when both `limit_price` and `stop_price` are set.

        The order ID is not auto-generated at event creation but must be generated by
        the caller.
        This allows the caller to keep track of submitted orders via their order ID.

        Implementation Note:
            More complex order types should be approximated within the strategy logic
            via cancel-and-resubmit mechanisms.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
            trade_side:
                Direction of the order (buy or sell).
            qty:
                Number of contracts or shares to trade.
            limit_price:
                Limit price for the order.
            stop_price:
                If set, the order becomes a stop-limit order that activates at
                this price.
                If not set, order becomes a limit order.
        """

        # fmt: off
        trade_side:     TradeSide
        qty:            Quantity

        limit_price:    ScaledPrice
        stop_price:     ScaledPrice | None = None  # becomes stop-limit order if set
        # fmt: on

    @dataclass(frozen=True, kw_only=True)
    class CancellationRequest(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that the trading system requests to cancel a
        previously submitted order.

        Implementation Note:
            Order modification is not supported.
            To modify an order, cancel the existing order and submit a new
            `OrderRequest`.
            This significantly reduces the surface area and complexity of the system.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
        """

        pass

    @dataclass(frozen=True, kw_only=True)
    class OrderSubmitted(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that an order has been accepted by the broker and is
        now live on the market.

        The `synthetic` field is used to indicate whether the event is synthetic (if
        `True`) or not (if `False`).
        A synthetic `OrderSubmitted` event is emitted by a broker connector component
        on (re-)connect to communicate to the system the working orders that already
        exist for the account (it does not represent an acceptance of an order request
        submitted during this run).

        Implementation Note:
            The mechanism of emitting synthetic events to inform the system of existing
            account state on (re-)connect allows the broker account to be the single
            source of truth (SSOT) for our trading system, which makes a system crash
            easier to recover from.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
            source_request:
                The original `OrderRequest` that led to this submission.
            synthetic:
                If `True`, this event was emitted on (re-)connect to restore the
                system's view of working orders already present at the broker.
        """

        # fmt: off
        source_request: "DomainEvents.OrderRequest"
        synthetic:      bool = False
        # fmt: on

    @dataclass(frozen=True, kw_only=True)
    class OrderRejected(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that an order has been rejected by the broker.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
            source_request:
                The original `OrderRequest` that was rejected.
            reason:
                Broker-provided explanation for the rejection.
        """

        # fmt: off
        source_request: "DomainEvents.OrderRequest"
        reason:         Reason
        # fmt: on

    @dataclass(frozen=True, kw_only=True)
    class OrderCancelled(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that an order has been cancelled successfully by the
        broker and is thus no longer live in the market.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
        """

        pass

    @dataclass(frozen=True, kw_only=True)
    class CancellationRejected(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that a cancellation request has been rejected by
        the broker.
        The order should still be assumed to be live on the market.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
            reason:
                Broker-provided explanation for the rejection.
        """

        reason: Reason

    @dataclass(frozen=True, kw_only=True)
    class Fill(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that an order has been (partially or fully) filled.

        Each fill carries the post-fill position state (`signed_position_size` and
        `position_cost_basis`) as reported by the broker, which is the single source
        of truth (SSOT) for position accounting. This eliminates the need for
        computing position sizes and cost bases internally and avoids having to
        track instrument-specific commissions and fees.

        The `synthetic` field is used to indicate whether the event is synthetic (if
        `True`) or not (if `False`).
        A synthetic `Fill` event is emitted by a broker connector component on
        (re-)connect to communicate to the system the position state that already
        exists for the account (it does not represent an actual execution).

        Implementation Note:
            The mechanism of emitting synthetic events to inform the system of existing
            account state on (re-)connect allows the broker account to be the single
            source of truth (SSOT) for our trading system, which makes a system crash
            easier to recover from.

            The `position_cost_basis` value is taken directly from the broker.
            For strategies relying on commissions and fees being integrated into the
            cost basis of the position, the broker should be configured to include
            commissions and fees in the reported cost basis.

            An order that fills at multiple price levels produces multiple `Fill`
            events, one per partial execution.
            Each carries the updated aggregate position state after that particular
            partial fill.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
            trade_side:
                Direction of the fill (buy or sell).
            filled_qty:
                Number of contracts or shares filled in this execution.
            remaining_qty:
                Number of contracts or shares still outstanding on the order.
                Zero indicates the order is fully filled.
            fill_price:
                Price at which this fill was executed.
            synthetic:
                If `True`, this event was emitted on (re-)connect to restore the
                system's view of positions already present at the broker.
            signed_position_size:
                Net position size after this fill, as reported by the broker.
            position_cost_basis:
                Average entry price of the position after this fill, as reported
                by the broker. `None` if the position is flat.
        """

        # fmt: off
        trade_side:             TradeSide
        filled_qty:             Quantity
        remaining_qty:          Quantity
        fill_price:             ScaledPrice

        synthetic:              bool = False

        signed_position_size:   SignedPositionSize
        position_cost_basis:    ScaledPrice | None = None
        # fmt: on

    @dataclass(frozen=True, kw_only=True)
    class OrderExpired(EventMessageBase, InstrumentRelated, OrderRelated):
        """
        Event message indicating that an order has expired and is no longer live
        on the market.

        Parameters:
            timestamp:
                Timestamp of event creation.
            instrument:
                The specific instrument this event relates to.
            order_id:
                Unique system-internal identifier of the order this event relates to.
        """

        pass


class SystemEvents:
    """
    Namespace class for system-level event messages.
    """

    @dataclass(frozen=True, kw_only=True)
    class ShutdownDecision(EventMessageBase):
        """
        Event message that represents the decision that the system should shut down.

        Parameters:
            timestamp: Timestamp of event creation.
            reason: Why the system is shutting down.
        """

        reason: Reason
